### ISSUE TITLE
Conic Gradient demo misbehaving on Canary

### ISSUE THREAD

**Issue by vidhill** [iamvdo/houdini-experiments#4]
Hi, 

It appears that your conic gradient Paint Worklet demo is not working in Chrome Canary any more..
I see a black box.. 

I think it is because Canary (with the experimental features flag on) supports css conic-gradient 

I know you have the css for css conic gradients there, 
but I think your js is applying a class that overrides that rule with `background: paint(conic-gradient`

**Comment by vidhill** [comment]
I think the solution is to change the `@supports` rule to..

```css
@supports (background: paint(id)) and (not (conic-gradient(red, magenta) ))
```

I'm not 100% sure if that's right, I haven't done much with `@supports`

**Comment by iamvdo** [comment]
Thanks for reporting. Seems like a bug with Paint API and Typed OM. Arguments from the `paint()` function are no longer parsed as array. So I hot fixed it. :man_shrugging:
