### ISSUE TITLE
out of date https://css-houdini.rocks/svg-path-layout (and other async based demos)

### ISSUE THREAD

**Issue by laurentperez** [iamvdo/houdini-experiments#6]
Hi

Chrome Canary M78

78.0.3887.0 (Build officiel) canary (64 bits)
Révision | 8a7bd486e7da7bfcc2cc336ef162d6400de4e57a-refs/branch-heads/3887@{#1}

https://css-houdini.rocks/svg-path-layout used to work fine
Now it console logs

The layout function must be async or return a promise, falling back to block layout.

This is due to https://chromium.googlesource.com/chromium/src/+/9c224451fb63df743fbd510052458e088a438517

Is an update planned ?

(posted orignaly as https://github.com/w3c/css-houdini-drafts/issues/934)

**Comment by iamvdo** [comment]
Thanks for the issue.
Not sure how to handle this. Converting `intrinsicSizes()` and `layout()` functions from generators to promises do not seem to work as-is.
Plus, it fails in versions <78.

So, I will wait for now. Follow GoogleChromeLabs/houdini-samples#62

**Comment by iamvdo** [comment]
Fix with 7f9a93d1240f815b7a59df8b9f45d8afa2d5792a
